spring:
  application:
    name: convertlab-backend

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB        # per file limit
      max-request-size: 25MB    # total body limit

server:
  servlet:
    context-path: /api
  tomcat:
    max-swallow-size: 200MB

temp:
  folder: temp-files
  ttl-ms: 1800_000 #30mins
  cleanup-interval-ms: 1800_000 #30mins

app:
  cors:
    allowed-origins: https://www.easyconvertlab.com,http://localhost:4200